# Authentication
### Sign in
POST {{host}}/api/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "test1",
  "password": "123S@31aq2"
}

### Sign up
POST {{host}}/api/auth/sign-up
Accept: application/json
Content-Type: application/json

{
  "fullName": "Test account 01",
  "username": "test1",
  "password": "123S@31a2"
}

###
# Category
### Get all category
GET {{host}}/api/category
Content-Type: application/json

### Upsert new category
POST {{host}}/api/category
Content-Type: application/json

{
  "uuid": "",
  "name": "Chén",
  "price": 35000
}

### Delete category
DELETE {{host}}/api/category/kg/8c8a57b0-5a4f-4f87-bbd0-29aec2a85c66
Content-Type: application/json

{
  "unit": "KG"
}

###

# Inventory
### Get all Inventory
GET {{host}}/api/inventory
Content-Type: application/json

### Get inventory report
GET {{host}}/api/inventory/2024062801/report
Content-Type: application/json

### Get inventory report
GET {{host}}/api/inventory/2024071201/report
Content-Type: application/json

### Upsert new Inventory
POST {{host}}/api/inventory
Content-Type: application/json

{
  "price": 121231333,
  "grossWeight": "11231",
  "status": "CREATED",
  "source": "http://test",
  "unit": "kg"
}

###

# Product
### Get product List
GET {{host}}/api/product
Content-Type: application/json

### Upsert new Inventory
POST {{host}}/api/product/print-barcode
Content-Type: application/json

{
  "byDateId": "121231333"
}

###

# Invoice
### Upsert new Invoice
POST {{host}}/api/invoice
Content-Type: application/json

{
  "paymentType": "CASH",
  "items": [
    {
      "byDateId": "202407020006",
      "name": "Tô ăn mì",
      "quantity": 1,
      "weight": 0.23,
      "price": 40000,
      "total": 40000,
      "unit": "Chiếc",
      "stock": 5,
      "originalStock": 6
    }
  ],
  "stacks": [
    {
      "name": "Lam (kg)",
      "categoryUuidByKg": "869289e5-bb08-42d0-85b9-c2193ca6b2c7",
      "weight": 0.18,
      "price": 120000,
      "total": 21600,
      "items": [
        {
          "byDateId": "202407020007",
          "name": "Dĩa nhật",
          "quantity": 1,
          "weight": 0.18,
          "price": 120000,
          "total": 21600,
          "unit": "Kg",
          "stock": 3,
          "originalStock": 4
        }
      ]
    },
    {
      "name": "Mộc (kg)",
      "categoryUuidByKg": "70c5509e-fc6e-4730-920d-69de4c829e68",
      "weight": 1.65,
      "price": 100000,
      "total": 165000,
      "items": [
        {
          "byDateId": "202406270002",
          "name": "Chén mộc",
          "quantity": 3,
          "weight": 0.3,
          "price": 100000,
          "total": 150000,
          "unit": "Kg",
          "stock": 0,
          "originalStock": 3
        }
      ]
    }
  ],
  "actualPrice": 226600
}


### Get Invoice list
GET {{host}}/api/invoice

### Upsert sale
POST {{host}}/api/sale
Content-Type: application/json

{
  "name": "Sale 001",
  "startDate": "2024-01-01",
  "steps": "1*p + (n-1)*p*80%",
  "condition": "n >= 2",
  "isActive": true
}

### Get all Sales
GET {{host}}/api/sale

### SEED REport
GET {{host}}/api/report/seed

### recent-income
GET {{host}}/api/report/recent-income

### today-insight
GET {{host}}/api/report/today-insight

### Cron REport
GET {{host}}/api/report/cron

### compare-month-income
GET {{host}}/api/report/compare-month-income

### Get period incom
GET {{host}}/api/report/period-income?from=2024-08-01&to=2024-08-31
