
### Sign in
POST {{host}}/api/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "username": "test1",
  "password": "123S@31aq2"
}

### Sign up
POST {{host}}/api/auth/sign-up
Accept: application/json
Content-Type: application/json

{
  "fullName": "Test account 01",
  "username": "test1",
  "password": "123S@31a2"
}

### Get all category
GET {{host}}/api/category
Content-Type: application/json

### Create new category
POST {{host}}/api/category
Content-Type: application/json

{
  "uuid": "",
  "name": "Chén",
  "price": 35000
}

### Get all Inventory
GET {{host}}/api/inventory
Content-Type: application/json

### Create new Inventory
POST {{host}}/api/inventory
Content-Type: application/json

{
  "price": 121231333,
  "grossWeight": "11231",
  "status": "CREATED",
  "source": "http://test",
  "unit": "kg"
}


### Create new Inventory
POST {{host}}/api/product/print-barcode
Content-Type: application/json

{
  "byDateId": "121231333"
}